# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: $NODE_VERSION
  pre_build:
    commands:
      - echo Pre-build Installing source yarn dependencies...
      - yarn install:all
      - echo All installed
  build:
    commands:
      - echo Build
      - yarn build
      - echo All builded
  post_build:
    commands:
      - echo Run all tests
      - yarn test
      - echo All tests has passed
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - package.json
    - yarn.lock
    - node_modules/**/*
