# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Pre-build Installing source yarn dependencies...
      - yarn build
      - echo Builded and all dependencies installed
  build:
    commands:
      - echo Check tests
  post_build:
    commands:
      - echo Run all tests
      - yarn test
      - echo All tests passed
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - package.json
    - yarn.lock
    - src/**/*
    - node_modules/**/*
