version: '3'

services:
  mongo:
    container_name: mongo_fazenda
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
volumes: 
  data: