import {
  PRODUCT_CATEGORY_DESCRIPTION_MAX_STRING_LENGTH,
  PRODUCT_CATEGORY_DESCRIPTION_MIN_STRING_LENGTH,
} from './ProductCategory.domain-entity';
export const ERROR_PRODUCT_CATEGORY_DESCRIPTION_LENGTH = `Product Category Description length Should be between ${PRODUCT_CATEGORY_DESCRIPTION_MIN_STRING_LENGTH} and ${PRODUCT_CATEGORY_DESCRIPTION_MAX_STRING_LENGTH}`;
