import {
  MAX_PRODUCT_CATEGORY_DESCRIPTION_LENGTH,
  MIN_PRODUCT_CATEGORY_DESCRIPTION_LENGTH,
} from './product-category.domain-entity';
export const ERROR_PRODUCT_CATEGORY_DESCRIPTION_LENGTH = `Product Category Description length Should be between ${MIN_PRODUCT_CATEGORY_DESCRIPTION_LENGTH} and ${MAX_PRODUCT_CATEGORY_DESCRIPTION_LENGTH}`;
