import {
  MAX_BASKET_CATEGORY_DESCRIPTION_LENGTH,
  MIN_BASKET_CATEGORY_DESCRIPTION_LENGTH,
} from './basketCategory.domain-entity';
export const ERROR_BASKET_CATEGORY_DESCRIPTION_LENGTH = `Product Category Description length Should be between ${MIN_BASKET_CATEGORY_DESCRIPTION_LENGTH} and ${MAX_BASKET_CATEGORY_DESCRIPTION_LENGTH}`;
