import {
  MAX_BASKET_CATEGORY_CHANGE_LIMIT_VALUE,
  MAX_BASKET_CATEGORY_DESCRIPTION_LENGTH,
  MIN_BASKET_CATEGORY_DESCRIPTION_LENGTH,
} from './BasketCategory.domain-entity';
export const ERROR_BASKET_CATEGORY_DESCRIPTION_LENGTH = `Product Category Description length Should be between ${MIN_BASKET_CATEGORY_DESCRIPTION_LENGTH} and ${MAX_BASKET_CATEGORY_DESCRIPTION_LENGTH}`;
export const ERROR_BASKET_CATEGORY_MAX_VALUE = `Max change limit should be less than ${MAX_BASKET_CATEGORY_CHANGE_LIMIT_VALUE}`;
