import {
  DELIVERY_STATUS_DESCRIPTION_MAX_STRING_LENGTH,
  DELIVERY_STATUS_DESCRIPTION_MIN_STRING_LENGTH,
  DELIVERY_INFO_DESCRIPTION_MAX_STRING_LENGTH,
  DELIVERY_INFO_DESCRIPTION_MIN_STRING_LENGTH,
} from './delivery-status.domain-entity';
export const ERROR_DELIVERY_STATUS_LENGTH_DESCRIPTION = `Delivery Status Description length Should be between ${DELIVERY_STATUS_DESCRIPTION_MIN_STRING_LENGTH} and ${DELIVERY_STATUS_DESCRIPTION_MAX_STRING_LENGTH}`;
export const ERROR_INFO_STATUS_LENGTH_DESCRIPTION = `Delivery Info Description length Should be between ${DELIVERY_INFO_DESCRIPTION_MIN_STRING_LENGTH} and ${DELIVERY_INFO_DESCRIPTION_MAX_STRING_LENGTH}`;
