import {
  COUPON_CODE_MAX_STRING_LENGTH,
  COUPON_CODE_MIN_STRING_LENGTH,
  COUPON_DESCRIPTION_MAX_STRING_LENGTH,
  COUPON_DESCRIPTION_MIN_STRING_LENGTH,
  COUPON_PERCENTAGE_MAX_VALUE,
  COUPON_PERCENTAGE_MIN_VALUE,
  COUPON_MIN_EXPIRATION_DATE_IN_DAYS,
  COUPON_MIN_VALUE,
} from './Coupon.domain-entity';
export const ERROR_COUPON_LENGTH_DESCRIPTION = `Coupon Description length Should be between ${COUPON_DESCRIPTION_MIN_STRING_LENGTH} and ${COUPON_DESCRIPTION_MAX_STRING_LENGTH}`;
export const ERROR_COUPON_LENGTH_CODE_DESCRIPTION = `Coupon Code length Should be between ${COUPON_CODE_MIN_STRING_LENGTH} and ${COUPON_CODE_MAX_STRING_LENGTH}`;
export const ERROR_COUPON_PERCENTAGE_INVALID_RANGE = `Coupon Percentage Should be between ${COUPON_PERCENTAGE_MIN_VALUE} and ${COUPON_PERCENTAGE_MAX_VALUE}`;
export const ERROR_COUPON_EXPIRATION_RANGE_DAY = `Expiration should be min ${COUPON_MIN_EXPIRATION_DATE_IN_DAYS} day(s)`;
export const ERROR_COUPON_MIN_VALUE = `Coupon value should be min ${COUPON_MIN_VALUE}`;
